export const categories=['Autres','Charcuterie','Viandes','Poissons','Produits laitiers','Fruits et légumes','Épicerie','Surgelés'];
const rules=[[/jambon|saucisson|lardon|pâté|charcuterie|chorizo/i,'Charcuterie',['charcuterie','réfrigéré']],[/poulet|dinde|bœuf|boeuf|steak|porc|agneau|veau/i,'Viandes',['viande','réfrigéré']],[/saumon|thon|cabillaud|crevette|poisson/i,'Poissons',['poisson','réfrigéré']],[/lait|fromage|yaourt|beurre|crème/i,'Produits laitiers',['laitier','réfrigéré']],[/tomate|carotte|salade|pomme|courgette|légume|fruit/i,'Fruits et légumes',['végétal']],[/riz|pâte|farine|huile|sucre|conserve/i,'Épicerie',['épicerie']]];
export function classify(text){const rule=rules.find(r=>r[0].test(text));const tags=rule?[...rule[2]]:[];if(/jambon|porc|lardon|saucisson|chorizo/i.test(text))tags.push('porc');if(/surgelé|congelé/i.test(text))return{type:'Surgelés',tags:[...new Set([...tags,'surgelé'])]};return{type:rule?.[1]||'Autres',tags};}
export function localDate(d=new Date()){return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;}
export function parseDate(s){const m=s.match(/\b(\d{1,2})[./-](\d{1,2})[./-](\d{4}|\d{2})\b/);if(!m)return '';let year=Number(m[3]);if(year<100)year+=2000;const d=new Date(year,Number(m[2])-1,Number(m[1]));return d.getFullYear()===year&&d.getMonth()===Number(m[2])-1&&d.getDate()===Number(m[1])?localDate(d):'';}
export function extract(text){const lines=text.split(/\n/).map(s=>s.trim()).filter(Boolean);const product=lines.find(s=>rules.some(r=>r[0].test(s)));const lot=text.match(/\b(?:lot|batch)\s*(?:n[°oº]?|num[eé]ro)?\s*[:#.-]?\s*([A-Z0-9][A-Z0-9./_-]*)/i)?.[1]||'';const dateLine=lines.find(s=>/DLC|DDM|consommer|péremption|expiration/i.test(s));const expiry=dateLine?parseDate(dateLine+' '+(lines[lines.indexOf(dateLine)+1]||'')):'';return{name:product||'',lot,expiry,dateKind:dateLine&&/DDM|de préférence/i.test(dateLine)?'DDM':'DLC',...classify(product||'')};}
export function deadline(r){return [r.expiry,r.openExpiry].filter(Boolean).sort()[0]||'';}
export function urgency(r,today=localDate()){if(r.state==='blocked'||r.state==='withdrawn')return'blocked';if(r.state==='used')return'used';const end=deadline(r);if(!end)return'none';const days=Math.round((Date.parse(end+'T12:00:00Z')-Date.parse(today+'T12:00:00Z'))/86400000);return days<0?'expired':days<=3?'soon':'ok';}
export function csvCell(value){let s=String(value??'');if(/^[\s]*[=+@-]/.test(s))s="'"+s;return '"'+s.replaceAll('"','""')+'"';}
