import {dueReminders,validReminder} from './reminders.mjs';
import {localDate,csvCell} from './logic.mjs';
const $=id=>document.getElementById(id);
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const date=s=>new Date(s+'T12:00:00').toLocaleDateString('fr-FR');
export function createNotifications(db,{openRecord,notify}){
 let entries=[],records=[],leadDays=3,queue=Promise.resolve();
 function tx(stores,mode,action){return new Promise((resolve,reject)=>{const t=db.transaction(stores,mode);let r;try{r=action(t);}catch(e){t.abort();reject(e);return;}t.oncomplete=()=>resolve(r?.result);t.onerror=()=>reject(t.error);t.onabort=()=>reject(t.error||new Error('Stockage interrompu'));});}
 async function read(){entries=await tx(['notifications'],'readonly',t=>t.objectStore('notifications').getAll());const p=await tx(['settings'],'readonly',t=>t.objectStore('settings').get('reminders'));leadDays=Math.max(3,Math.min(30,p?.leadDays||3));$('leadDays').value=leadDays;render();}
 function render(){const unread=entries.filter(n=>!n.readAt).length;$('notificationBadge').textContent=unread;$('notificationBadge').hidden=!unread;$('notificationCount').textContent=`${entries.length} alerte${entries.length>1?'s':''} · ${unread} non lue${unread>1?'s':''}`;
 const q=$('notificationSearch').value.toLocaleLowerCase('fr');const list=entries.filter(n=>(!q||[n.name,n.lot,n.type].join(' ').toLocaleLowerCase('fr').includes(q))&&(!$('notificationState').value||($('notificationState').value==='unread'?!n.readAt:!!n.readAt))&&(!$('notificationKind').value||n.kind===$('notificationKind').value)&&(!$('notificationFrom').value||n.day>=$('notificationFrom').value)&&(!$('notificationTo').value||n.day<=$('notificationTo').value)).sort((a,b)=>b.createdAt.localeCompare(a.createdAt)||a.expiry.localeCompare(b.expiry));
 $('notificationList').innerHTML=list.length?list.map(n=>`<article class="notification-card ${n.readAt?'':'unread'}"><div><span class="badge ${n.kind==='expired'?'bad':'warn'}">${n.days<0?'Dépassée depuis '+Math.abs(n.days)+' jour(s)':n.days===0?'Échéance aujourd’hui':'J−'+n.days}</span><h3>${esc(n.name)}</h3><p>Lot ${esc(n.lot)} · ${esc(n.type)}</p><p>${esc(n.dateKind)} : ${date(n.expiry)}</p><p class="hint">Alerte créée le ${esc(new Date(n.createdAt).toLocaleString('fr-FR'))}<br>${n.readAt?'Lue le '+esc(new Date(n.readAt).toLocaleString('fr-FR')):'Non lue'} · Dans l’application</p></div><div class="notification-actions"><button data-notification-open="${esc(n.recordId)}">Voir la fiche</button><button data-notification-read="${esc(n.id)}">${n.readAt?'Marquer non lue':'Marquer lue'}</button></div></article>`).join(''):'<div class="empty"><h3>Aucune alerte à afficher</h3><p>Les alertes apparaissent à partir de J−'+leadDays+', puis chaque jour où vous utilisez le site. Aucun ancien rappel n’est inventé.</p></div>';
 }
 async function syncRecords(next){records=next;queue=queue.catch(()=>{}).then(async()=>{const p=await tx(['settings'],'readonly',t=>t.objectStore('settings').get('reminders'));leadDays=p?.leadDays||3;const candidates=dueReminders(records,localDate(),leadDays);await tx(['notifications'],'readwrite',t=>{const s=t.objectStore('notifications');for(const n of candidates){const get=s.get(n.id);get.onsuccess=()=>{if(!get.result)s.add(n);};}});await read();});return queue;}
 async function mark(id){const n=entries.find(e=>e.id===id);if(!n)return;await tx(['notifications'],'readwrite',t=>t.objectStore('notifications').put({...n,readAt:n.readAt?null:new Date().toISOString()}));await read();}
 const safely=fn=>async(...args)=>{try{await fn(...args);}catch{notify('Impossible de mettre à jour les alertes. Vérifiez le stockage du navigateur.');}};
 $('showNotifications').onclick=()=>{$('notificationCenter').showModal();render();};$('closeNotifications').onclick=()=>$('notificationCenter').close();
 $('notificationList').onclick=safely(async e=>{const read=e.target.closest('[data-notification-read]'),open=e.target.closest('[data-notification-open]');if(read)await mark(read.dataset.notificationRead);if(open){const r=records.find(r=>r.id===open.dataset.notificationOpen);if(!r){notify('La fiche a été supprimée. Son alerte reste dans l’historique.');return;}$('notificationCenter').close();openRecord(r);}});
 $('readAllNotifications').onclick=safely(async()=>{await tx(['notifications'],'readwrite',t=>{for(const n of entries.filter(n=>!n.readAt))t.objectStore('notifications').put({...n,readAt:new Date().toISOString()});});await read();});
 $('reminderSettings').onsubmit=safely(async e=>{e.preventDefault();const v=Number($('leadDays').value);if(!Number.isInteger(v)||v<3||v>30){notify('Choisissez un délai entre 3 et 30 jours.');return;}await tx(['settings'],'readwrite',t=>t.objectStore('settings').put({id:'reminders',leadDays:v}));await syncRecords(records);notify('Délai des rappels enregistré.');});
 for(const id of ['notificationSearch','notificationState','notificationKind','notificationFrom','notificationTo'])$(id).addEventListener(id==='notificationSearch'?'input':'change',render);
 $('resetNotifications').onclick=()=>{for(const id of ['notificationSearch','notificationState','notificationKind','notificationFrom','notificationTo'])$(id).value='';render();};
 $('exportNotifications').onclick=()=>{const rows=[['Produit','Lot','Catégorie','Type de date','Échéance','Jour du rappel','Jours restants','Créée le','Lue le','Canal'],...entries.map(n=>[n.name,n.lot,n.type,n.dateKind,n.expiry,n.day,n.days,n.createdAt,n.readAt||'','Application'])];const url=URL.createObjectURL(new Blob(['\uFEFF'+rows.map(r=>r.map(csvCell).join(';')).join('\r\n')],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download=`historique-alertes-${localDate()}.csv`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
 async function snapshot(){await queue;return{notifications:await tx(['notifications'],'readonly',t=>t.objectStore('notifications').getAll()),settings:await tx(['settings'],'readonly',t=>t.objectStore('settings').get('reminders'))||{id:'reminders',leadDays:3}};}
 function validateBackup(data){return (data.notifications===undefined||Array.isArray(data.notifications)&&data.notifications.every(validReminder))&&(data.settings===undefined||data.settings&&Number.isInteger(data.settings.leadDays)&&data.settings.leadDays>=3&&data.settings.leadDays<=30);}
 const update=safely(()=>syncRecords(records));const interval=setInterval(()=>{if(!document.hidden)update();},60000);document.addEventListener('visibilitychange',()=>{if(!document.hidden)update();});window.addEventListener('pagehide',()=>clearInterval(interval),{once:true});
 return{syncRecords,snapshot,validateBackup};
}
